# Generated by Django 6.0.7 on 2026-07-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('PROJECT_MANAGER', 'Project Manager'), ('TEAM_LEAD', 'Team Lead'), ('ENGINEER', 'Engineer')], max_length=30),
        ),
    ]
