# Generated by Django 6.0.7 on 2026-07-14 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=150)),
                ('experience_years', models.DecimalField(decimal_places=1, max_digits=4)),
                ('availability_percentage', models.PositiveSmallIntegerField(default=100)),
                ('current_capacity_hours', models.DecimalField(decimal_places=2, default=40, max_digits=6)),
                ('status', models.CharField(choices=[('WFH', 'Work From Home'), ('ACTIVE', 'Active'), ('BUSY', 'Busy')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.employee')),
            ],
            options={
                'db_table': 'employee_profiles',
            },
        ),
    ]
