# Generated by Django 6.0.7 on 2026-07-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employeeprofile'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='employee_profiles', to='project.skill'),
        ),
    ]
