# Generated by Django 6.0.7 on 2026-07-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employeeprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='status',
            field=models.CharField(choices=[('WFM', 'WFM'), ('ACTIVE', 'Active'), ('BUSY', 'Busy')], default='ACTIVE', max_length=20),
        ),
    ]
