# Generated by Django 6.0.7 on 2026-07-16 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_employeeprofile_status'),
        ('project', '0003_skill_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='skills',
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency_level', models.PositiveSmallIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skill_relations', to='accounts.employeeprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skill_relations', to='project.skill')),
            ],
            options={
                'db_table': 'employee_skills',
                'unique_together': {('employee', 'skill')},
            },
        ),
    ]
