# Generated by Django 6.0.7 on 2026-07-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_employeeprofile_skills_employeeskill'),
        ('project', '0003_skill_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='employee_profiles', through='accounts.EmployeeSkill', to='project.skill'),
        ),
    ]
