# Generated by Django 6.0.7 on 2026-07-28 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20260716_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('PROJECT_MANAGER', 'Project Manager'), ('TEAM_LEAD', 'Team Lead'), ('ENGINEER', 'Engineer')], max_length=15, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
