# Generated by Django 6.0.7 on 2026-08-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='performance_points',
            field=models.IntegerField(default=0),
        ),
    ]
