# Generated by Django 6.0.7 on 2026-08-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_employeeprofile_performance_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='performance_points',
        ),
    ]
