# Generated by Django 6.0.7 on 2026-07-15 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_skills', to='project.skill'),
        ),
    ]
