# Generated by Django 6.0.7 on 2026-07-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_skill_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
