# Generated by Django 6.0.7 on 2026-07-24 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='project.project')),
            ],
            options={
                'db_table': 'project_holidays',
                'ordering': ['date'],
                'unique_together': {('project', 'date')},
            },
        ),
    ]
