# Generated by Django 6.0.7 on 2026-07-27 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projectholiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectHoliday',
        ),
    ]
