# Generated by Django 6.0.7 on 2026-07-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_jira_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='jira_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
