# Generated by Django 6.0.7 on 2026-08-03 08:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_employee_role'),
        ('project', '0009_alter_project_jira_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='jira_id',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Jira ID must start with an uppercase letter and be uppercase alphanumeric.', regex='^[A-Z][A-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='number_of_days',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Project ID must be alphanumeric and uppercase.', regex='^[A-Z0-9\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_size',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
