# Generated by Django 6.0.7 on 2026-08-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_project_description_alter_project_jira_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='jira_board_id',
            field=models.CharField(blank=True, help_text='The ID of the primary Jira board for this project, used to construct backlog URLs.', max_length=50, null=True),
        ),
    ]
