# Generated by Django 6.0.7 on 2026-07-16 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20260716_1119'),
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('matching_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('recommended_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_recommendations', to='accounts.employeeprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='sprints.sprinttask')),
            ],
            options={
                'db_table': 'task_recommendations',
                'ordering': ['-generated_at'],
            },
        ),
    ]
