# Generated by Django 6.0.7 on 2026-07-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_taskrecommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='name',
            new_name='milestone',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='goal',
        ),
        migrations.AlterField(
            model_name='sprinttask',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN_PROGRESS'), ('RESOLVED', 'RESOLVED'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=20),
        ),
    ]
