# Generated by Django 6.0.7 on 2026-07-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0003_rename_name_sprint_milestone_remove_sprint_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='backlog_project_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='backlog_version_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
