# Generated by Django 6.0.7 on 2026-07-21 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0004_sprint_backlog_project_id_sprint_backlog_version_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
