# Generated by Django 6.0.7 on 2026-07-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0005_sprint_completed_at_sprint_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
