# Generated by Django 6.0.7 on 2026-07-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0007_alter_sprint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprinttask',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sprinttask',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
