# Generated by Django 6.0.7 on 2026-07-29 03:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0008_sprinttask_is_deleted_sprinttask_synced_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='sprints.sprint')),
            ],
            options={
                'db_table': 'sprint_holidays',
                'ordering': ['date'],
                'unique_together': {('sprint', 'date')},
            },
        ),
    ]
