# Generated by Django 6.0.7 on 2026-07-30 09:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0009_sprintholiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='sprints.sprint')),
            ],
            options={
                'db_table': 'sprint_notes',
                'ordering': ['-date'],
                'unique_together': {('sprint', 'date')},
            },
        ),
    ]
