# Generated by Django 6.0.7 on 2026-08-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0010_sprintnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintnote',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notes_attachments/'),
        ),
    ]
