# Generated by Django 6.0.7 on 2026-08-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0011_sprintnote_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprinttask',
            name='category',
            field=models.CharField(default='UI', max_length=255),
        ),
    ]
