# Generated by Django 6.0.7 on 2026-08-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0012_alter_sprinttask_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprinttask',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
