# Generated by Django 6.0.7 on 2026-08-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0013_sprinttask_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprinttask',
            name='comment_count',
        ),
    ]
