# Generated by Django 6.0.7 on 2026-08-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0014_remove_sprinttask_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprinttask',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
