# Generated by Django 6.0.7 on 2026-08-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0015_sprinttask_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
