# Generated by Django 6.0.7 on 2026-08-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0016_sprint_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprinttask',
            name='read_comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
