# Generated by Django 6.0.7 on 2026-08-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0017_sprinttask_read_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprinttask',
            name='first_unread_comment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
