# Generated by Django 6.0.7 on 2026-08-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0018_sprinttask_first_unread_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprinttask',
            name='priority',
            field=models.CharField(choices=[('Low', 'LOW'), ('Normal', 'NORMAL'), ('High', 'HIGH'), ('Critical', 'CRITICAL')], default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='sprinttask',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
