# Generated by Django 6.0.7 on 2026-08-18 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_employeeprofile_performance_points'),
        ('sprints', '0019_alter_sprinttask_priority_alter_sprinttask_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMonthlyPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('on_time_tasks', models.IntegerField(default=0)),
                ('late_or_overdue_tasks', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('on_time_rate', models.CharField(default='100%', max_length=10)),
                ('rank', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_performances', to='accounts.employeeprofile')),
            ],
            options={
                'db_table': 'employee_monthly_performance',
                'ordering': ['rank', '-points'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
