# Generated by Django 6.0.7 on 2026-09-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0020_employeemonthlyperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='jira_sprint_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
