# Generated by Django 6.0.7 on 2026-09-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_jira_board_id'),
        ('sprints', '0021_sprint_jira_sprint_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'milestone'), name='unique_active_project_milestone'),
        ),
    ]
