# Generated by Django 6.0.7 on 2026-07-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraoauthtoken',
            name='workspace_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
