# Generated by Django 6.0.7 on 2026-07-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_integration', '0002_jiraoauthtoken_workspace_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraoauthtoken',
            name='workspace_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
