# Generated by Django 6.0.7 on 2026-08-07 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_employee_role'),
        ('jira_integration', '0003_alter_jiraoauthtoken_workspace_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraoauthtoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jira_tokens', to='accounts.employee'),
        ),
    ]
