# Generated by Django 6.0.7 on 2026-08-07 15:59

import jira_integration.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira_integration', '0004_jiraoauthtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraoauthtoken',
            name='access_token',
            field=jira_integration.models.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='jiraoauthtoken',
            name='refresh_token',
            field=jira_integration.models.EncryptedTextField(),
        ),
    ]
