# Generated by Django 6.0.7 on 2026-08-04 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0010_alter_project_description_alter_project_jira_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backlog_category_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog_categories', to='project.project')),
            ],
            options={
                'db_table': 'backlog_categories',
                'unique_together': {('project', 'name')},
            },
        ),
    ]
